name: Continuous Delivery

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetodevops.zip
          path: |
            '**.py'
            README.md